<!DOCTYPE html>
<html>
<body>

<h2>Edit Actor</h2>
<?php $linkEdit = $this->baseUrl($this->currentController.'/edit/id/'. $this->item->actor_id);?>
<form onsubmit="onSubmitForm(<?php echo $linkEdit ?>)" method="post">
    <label for="first_name">First name:</label><br>
    <input type="text" id="first_name" name="first_name" value="<?php echo $this->item->first_name ?>"><br>
    <label for="last_name">Last name:</label><br>
    <input type="text" id="last_name" name="last_name" value="<?php echo $this->item->last_name ?>"><br><br>
    <label for="last_updtae">Last update:</label><br>
    <input type="datetime-local" id="last_updtae" name="last_update" value="<?php echo $this->item->last_update ?>"><br><br>
    <input type="submit" value="Edit">
</form>

<script>
    function onSubmitForm(url){
        document.appForm.action = url;
        document.appForm.submit();
        return true;
    }
</script>

</body>
</html>

